### ISSUE TITLE
When deleting a single semester status, multiple statuses get deleted in descending order

### ISSUE THREAD

**Issue by kotlarz** [webkom/lego-webapp#848] opened 2017-10-26 14:33 UTC
When testing, 3 instead of 1 statuses were deleted when deleting a specific semester status.

**Comment by finnss** [comment] 2017-10-26 21:08
How to reproduce?

**Comment by kotlarz** [comment] 2017-10-27 09:55
Delete a semester status  from a company in bdb

**Comment by finnss** [comment] 2017-10-27 14:30
well duh << doesn't happen when I try that, got anything more specific? I tried Create Company -> add tons of semester statuses -> start deleting, which seems to work as intended.

**Comment by odinuge** [comment] 2017-10-27 14:33
Looks like it is a strange bug. I am able to reproduce it @finnss. When clicking "delete", the semsterStatus is deleted, but the modal is still visable, and clicking again deletes the next one. We should autoclose the modal when clicking delete too (Using a promise.then(), or just when clicked...).

**Comment by finnss** [comment] 2017-10-27 14:59
That's more of a problem with the modal, right? There used to be a bug with deleting semester statuses before the confirmation modal was even made, but I think I fixed it. Wondering if that's what @kotlarz is experiencing.

**Comment by kotlarz** [comment] 2017-10-28 13:18
I can't recall 100% what happen, but something among the lines of what @odinuge described sounds about right. Let me know if you fix and push anything to staging, I will try to reproduce it then @finnss.

**Comment by odinuge** [comment] 2017-10-28 18:12
This is a hell of a bug :laughing: - And it is not the modal's fault!

This is basically the key to the whole bug.
https://github.com/webkom/lego-webapp/blob/7887524df397cb06d5740c044c428cafec3523b1/app/routes/bdb/components/BdbDetail.js#L142

When deleting a semesterstatus, the status is removed from the semester and the global state. On the next render, the "next" `Semesterstatus` is rendered in a `SemesterStatusComponent` with the __same__ `key` as the deleted one. Therefore it is using the same component as the deleted one, and it is the bottom component in the list that is removed. And since we had a delete modal open for the semester we just deleted, it will still be open, with the new data it got in the next render...

When thinking about it, using indexes as keys is more or less just a way to remove the warning...
https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

React __0__ - BugBoys __1__

**Comment by finnss** [comment] 2017-10-28 22:25
Hahah really? Would never have guessed, I'll have to go through other places I might have used index as key. I'll get this fixed with a PR soon-ish. Good detective work @odinuge 👍

**Comment by odinuge** [comment] 2017-10-28 22:27
I have fixed quite a few bits in the Modal PR, so you can start by looking
at that :+1:

Den søn. 29. okt. 2017, 00:25 skrev Finn Julius Stephansen-Smith <
notifications@github.com>:

**Comment by finnss** [comment] 2017-10-28 22:28
edited out the "I'll fix" part ;o

**Comment by finnss** [comment] 2017-11-03 15:33
If it turns out the bug wasn't because of the `key={i}`, make another issue.

**Closed by finnss** 2017-11-03 15:33 UTC
Labels: bug
