### ISSUE TITLE
Email links opens a new tab

### ISSUE THREAD

**Issue by HoboKristian** [webkom/lego-webapp#1339] opened 2018-10-29 13:44 UTC
Currently clicking (all|some) email links opens a new tab in addition to the mailto:

For example clicking the interessegrupper@abakus.no link on this site:
https://abakus.no/pages/info/39-praktisk-informasjon

I believe the fix is to remove the target="_blank"

**Comment by HoboKristian** [comment] 2018-10-29 14:15
I just checked:
On Google Chrome 70.0.3538.77 it opens a new tab
On Opera 56.0.3051.52 it opens a new tab

On Safari 12.0 it does not open a new tab
On Firefox 63.0 it does not open a new tab

**Comment by odinuge** [comment] 2018-10-29 15:07
Hi!

This is because we use an editor called `medium-draft`, based on the `react`-lib `draft` from Facebook. The link component inside `medium-draft` adds `target="_blank"` to all links, including mailto's. Overriding that behavior would require a lot of duplicated scope, so I guess it should be adressed where the code is.

Link source:
https://github.com/brijeshb42/medium-draft/blob/0fd69124d1795500fbf8fcc23acace85b04fca25/src/components/entities/link.js#L28

After some googleing, I just got more unsure about what is the right behavior. I don't have any apple devices, so I am unable to test on Safari. This issue also looks strange https://stackoverflow.com/questions/42839716/ios-tel-and-mailto-links-only-work-with-target-blank.


Looks like this has been reported to `bugzilla` 8 (!!) years ago, but the issue is still open.
https://bugzilla.mozilla.org/show_bug.cgi?id=646552

:thinking:

**Comment by cherrybeans** [comment] 2018-10-31 19:54
I'll close this in light of the findings of @odinuge.

However as a nice personal fix for this, if you're a gmail user and have not set up Chrome to open mailto links directly in gmail, and it instead opens your system email client (which no one bothers to configure), I can recommend this article on fixing this: https://blog.hubspot.com/marketing/set-gmail-as-browser-default-email-client-ht

 Just realized that you could do this, and just fixed mine, so any new tabs opened are actually useful instead of something to click out of. Hope it helps!

**Closed by cherrybeans** 2018-10-31 19:54 UTC
